font_family      Iosevka Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

background_opacity 0.9

hide_window_decorations yes

scrollback_lines 1000000

map ctrl+shift+t no_op

# Send escape sequence for Shift+Enter (newline in Claude Code)
map shift+enter send_text all \x1b[13;2u
