theme = "kanagawa_transparent"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = "signature_help"
"F3" = ":format"
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]

[keys.insert]
C-s = "signature_help"
C-q = "collapse_selection"
A-f = "move_next_word_start"
A-b = "move_prev_word_start"

[keys.select]
D = "extend_to_line_end"

[editor.lsp]
auto-signature-help = false

